FROM node:latest

#RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app

WORKDIR /app

#COPY package*.json ./

COPY . .

RUN npm install

#COPY --chown=node:node . .

#USER node

EXPOSE 3000

CMD ["node", "app.js"]


