---

- name: Install ELK 7.7.0 and 6.7.2 Version
  hosts: localhost

  tasks:

  - name: update file permissions 770 version
    become: yes
    become_user: root
    shell: sudo chmod 700 ./configs/770/filebeat/config.yml; sudo chown root ./configs/770/filebeat/config.yml

  - name: update file permissions 672 version
    become: yes
    become_user: root
    shell: sudo chmod 700 ./configs/672/filebeat/config.yml; sudo chown root ./configs/672/filebeat/config.yml

  - name: Install ELKF
    raw: docker compose up -d
    
  - name: update Permission folders docker_volumes
    become: yes
    become_user: root
    shell: sudo chown -R are:are ./docker_volumes/

  - name: Upload Template ElasticSearch
    shell: curl -XPUT -H "Content-Type: application/json" -u elastic:MyPw123 -d @/home/are/elk/configs/770/elasticsearch/template/test.json http://localhost:9200/_template/test
    shell: curl -XPUT -H "Content-Type: application/json" -u elastic:MyPw123 -d @/home/are/elk/configs/672/elasticsearch/template/test.json http://localhost:9201/_template/test
