---

- name: Install ELK 7.7.0 and 6.7.2 Version
  hosts: localhost

  tasks:

  - name: update file permissions 770 version
    become: yes
    become_user: root
    shell: sudo chmod 700 ./configs/770/filebeat/config.yml; sudo chown root ./configs/770/filebeat/config.yml

  - name: update file permissions 672 version
    become: yes
    become_user: root
    shell: sudo chmod 700 ./configs/672/filebeat/config.yml; sudo chown root ./configs/672/filebeat/config.yml

  - name: Install ELKF
    raw: docker compose up -d
